server:
  port: 8082

spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hms_doctor_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: doctor_schema
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging:
  level:
    com.hms.doctor: DEBUG
    org.springframework.security: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


