server:
  port: 8086

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hms_notification_db
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: notification_schema

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: udemo8003@gmail.com
    password: oxpk duvs depn tkbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  
twilio:
  account:
    sid: ACc84b71a806c85d0aab43824106b237da
  auth:
    token: 52c677c21608df41e23736b37e3ebfa5
  phone:
    number: "8106544219"

logging:
  level:
    com.hms: DEBUG
    org.springframework.web: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


